In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
import generate_graph

In [6]:
from pathlib import Path
import os
import sys

project_root = Path.cwd().resolve().parents[1]
print(project_root)
sys.path.insert(0, str(project_root))

import lib.dataloader as dl

/vol/data/immuneML/cmsb26_project7

In [7]:
df = dl.load_kaggle_dataset("dataset_8")
df

Loading Kaggle dataset: dataset_8
Train path: /vol/data/keggel/train_datasets/train_datasets/train_dataset_8/
Loading cached dataset from /vol/data/keggel/train_datasets/train_datasets/train_dataset_8//_dataset.pkl...

,junction_aa,templates,sample,filename,label_positive,study_group_description,sex,age
0,CAAAGEDGYTF,2,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243
1,CAAAGGDNPTDTQYF,1,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243
2,CAAAIAEGYNEQFF,1,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243
3,CAAAPEGIYGYTF,1,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243
4,CAAAQSGGADTQYF,1,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243
...,...,...,...,...,...,...,...,...
93636518,YASRGRAHNQPQHF,1,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866
93636519,YASSRQGGSYEQYF,1,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866
93636520,YASTSGGNQPQHF,1,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866
93636521,YAWSVFELVIAPGTGTEAFF,1,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866
93636522,YSARDPRGPNTGELFF,1,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866

In [8]:
df = generate_graph.top_percent_cutoff(df, p=0.01)
df = df.reset_index(drop=True)
df

,junction_aa,templates,sample,filename,label_positive,study_group_description,sex,age,cummulative_perc
0,CAEVREVPYEQYF,4,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243,0.991695
1,CAFLTSGGAETQYF,11,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243,0.998952
2,CAFSPTRTGELFF,7,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243,0.997348
3,CAGAEGRNTEAFF,4,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243,0.991695
4,CAGEGDRVNYGYTF,4,e441182799ba6725d4ae80e218ce3116,e441182799ba6725d4ae80e218ce3116.tsv,False,FDR,F,39.945243,0.991695
...,...,...,...,...,...,...,...,...,...
1234880,CSVGVGENTEAFF,11,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866,0.998460
1234881,CSVRIGTGNTGELFF,4,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866,0.993724
1234882,CSVSRRGQGKETQYF,7,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866,0.996953
1234883,CSVTPGLAGGREQFF,6,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866,0.996506
1234884,CSVVEGSGDEQYF,4,d73b93a3bfb632580bce12bca0866506,d73b93a3bfb632580bce12bca0866506.tsv,True,T1D,F,15.635866,0.993724

In [5]:
df["sample"].value_counts()

sample
246ca03e43cc3f7cfa3ed5a15e4303b3    8321
6315ac52f03355b55bbf5b1fc7d97f14    5201
4cb9cd4877254d6b367621306890328d    4070
a46528b1202b492820a0548daf89a899    3421
2403d512cf7ae6f8e768b2fa75b6a487    3398
                                    ...
73774725e460b4b29e0a8a85833c5feb     553
0ac44b513e1cd6f803084a2cf220ecf2     537
3aaa1f17bfeff7f99e337f67fe5f37d1     520
bb3ecd98a4167666022f35e7c4ac249d     514
c3eff0c5d0c677b4e17ec09b9e72dc58     503
Name: count, Length: 908, dtype: int64

In [11]:
import numpy as np

import encoding.tcr_bert as tb

df_enc = tb.encode_sequences(df, seq_col="junction_aa", max_length=30)

['C A E V R E V P Y E Q Y F', 'C A F L T S G G A E T Q Y F', 'C A F S P T R T G E L F F', 'C A G A E G R N T E A F F', 'C A G E G D R V N Y G Y T F', 'C A G G T S L L M G T Q Y F', 'C A G P P V W R G N R Q S Y E Q Y F', 'C A G S G E P T D T Q Y F', 'C A H G T E A S P L H F', 'C A I A A F K L G Q G K I G E L F F', 'C A I G G Q G T D T Q Y F', 'C A I R G T M A G S T N T G E L F F', 'C A I R S T G G A K S F F', 'C A I S D G T S A S Y E Q Y F', 'C A I S D S W T T S V G E L F F', 'C A I S D W T S G T S S T D T Q Y F', 'C A I S E F G G R D N E Q F F', 'C A I S E F K G L A T S T D T Q Y F', 'C A I S E G G T S G D Y G N E Q F F', 'C A I S E G S D T T G E L F F']
['C S A S L T A G L I Y G Y T F', 'C S A S P I S G G D Y N E Q F F', 'C S A S R S F F', 'C S A S S G T P S Y N E Q F F', 'C S A T G T S S Y N E Q F F', 'C S A T P T G Q M G K E T Q Y F', 'C S A T S G G A G D R N E Q F F', 'C S A V G S E N Q P Q H F', 'C S A V V S G T G E L F F', 'C S F R V S H S Y N E Q F F', 'C S T Q T G D T E A F F', 'C S V A R H P N T G E L F F', 'C S V E T G Q S Y E Q Y F', 'C S V G D G L L G N Q P Q H F', 'C S V G Q G E P S G A N V L T F', 'C S V G V G E N T E A F F', 'C S V R I G T G N T G E L F F', 'C S V S R R G Q G K E T Q Y F', 'C S V T P G L A G G R E Q F F', 'C S V V E G S G D E Q Y F']

Tokenizing sequences: 100%|██████████| 1206/1206 [01:21<00:00, 14.74it/s]
Encoding sequences: 100%|██████████| 1206/1206 [19:34<00:00,  1.03it/s]

In [ ]:
# save mask and embeddings

_, _, embeddings = df_enc

save_path = "/vol/data/keggel/train_datasets/train_datasets/train_dataset_8"

np.save(save_path + "/embeddings.npy", embeddings)

In [ ]:
import numpy as np
save_path = "/vol/data/keggel/train_datasets/train_datasets/train_dataset_8"

embeddings = np.load(save_path + "/embeddings.npy")

In [ ]:
df_simplified = generate_graph.native_node_merge(df, embeddings)

In [18]:
idx = df.index[df["sample"] == "e441182799ba6725d4ae80e218ce3116"]  # directly take the first match
idx

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227],
      dtype='int64', length=2228)

In [21]:
embeddings[idx].shape

(2228, 768)

In [24]:
from sklearn.cluster import KMeans

k = 500

sample = embeddings[idx]

kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(sample)

labels

array([ 93, 340, 435, ...,  97,  36, 188], shape=(2228,), dtype=int32)

In [25]:
cluster_embeddings = kmeans.cluster_centers_
cluster_embeddings

array([[ 0.85577184, -1.13805   , -0.5106889 , ...,  0.25032258,
        -0.6116218 , -0.55089366],
       [ 1.5936358 , -0.7667846 , -0.2698797 , ...,  1.3458596 ,
         0.5895543 , -0.04811902],
       [ 1.0674667 , -0.6288656 ,  0.3218181 , ...,  1.2324518 ,
        -0.01031977, -0.19105873],
       ...,
       [ 2.1947415 , -2.4461136 ,  2.6672242 , ...,  0.08479452,
         1.5119071 ,  0.60968876],
       [ 0.5784817 ,  0.5970693 , -1.207242  , ..., -1.3329756 ,
        -0.8788754 ,  0.487073  ],
       [ 0.1704573 ,  0.06806922, -0.45676285, ...,  1.3508313 ,
        -0.12320688,  1.0217947 ]], shape=(500, 768), dtype=float32)

In [ ]:
def weighted_mean(group, emb_array):
    weights = group['weight'].values[:, None]  # make it (n_samples, 1)
    emb = emb_array[group.index]              # select embeddings for this group
    return (emb * weights).sum(axis=0) / weights.sum()

In [ ]:
def reduce_sample(df_sample, embeddings):
    idx = list(df_sample.index)
    sample_embeddings = embeddings[idx]