In [1]:
import scanpy as sc
import pandas as pd
import numpy as np

In [2]:
tcr_adat = sc.read_h5ad("human_tcr_reference_v2.h5ad")

In [3]:
df = pd.read_excel("SampleInformation_v2_5.xlsx", index_col=0)
df

,Individual ID,Tissue,Tissue Metatype,Cell Subsets,Disease,Disease Metatype,Cell Number,A_1,A_2,B_1,...,DQB1_2,DRB1_1,DRB1_2,Author,DOI or URL,Accession,GSM for GEX,Receptor Type,GSM for BCR,GSM for TCR
Sample ID,,,,,,,,,,,,,,,,,,,,,
10k_BEAM-T_Human_A0201_CMV_Flu_Covid_spikein_5pv2,10k_BEAM-T_Human_A0201_CMV_Flu_Covid_spikein_5pv2,PBMC,PBMC,Tetramer-enriched (BEAM-T),BEAM-T,BEAM-T,5593,NaN,NaN,NaN,...,NaN,NaN,NaN,10x Datasets,https://www.10xgenomics.com/cn/datasets/10k-hu...,NaN,NaN,TCR,NaN,NaN
10k_BEAM-T_Human_A1101_EBV_spikein_5pv2,10k_BEAM-T_Human_A1101_EBV_spikein_5pv2,PBMC,PBMC,Tetramer-enriched (BEAM-T),BEAM-T,BEAM-T,4073,NaN,NaN,NaN,...,NaN,NaN,NaN,10x Datasets,https://www.10xgenomics.com/cn/datasets/10k-hu...,NaN,NaN,TCR,NaN,NaN
10k_BEAM-T_Human_A2402_EBV_CMV_spikein_5pv2,10k_BEAM-T_Human_A2402_EBV_CMV_spikein_5pv2,PBMC,PBMC,Tetramer-enriched (BEAM-T),BEAM-T,BEAM-T,2445,NaN,NaN,NaN,...,NaN,NaN,NaN,10x Datasets,https://www.10xgenomics.com/cn/datasets/10k-hu...,NaN,NaN,TCR,NaN,NaN
5k_BEAM-T_Human_A0201_B0702_PBMC_5pv2_Multiplex,Multiplexed,PBMC,PBMC,Tetramer-enriched (BEAM-T),BEAM-T,BEAM-T,2389,NaN,NaN,NaN,...,NaN,NaN,NaN,10x Datasets,https://www.10xgenomics.com/cn/datasets/5k-hum...,NaN,NaN,TCR,NaN,NaN
10k_PBMC_5pv2_nextgem_Chromium_X,10k_PBMC_5pv2_nextgem_Chromium_X,PBMC,PBMC,NaN,BEAM-T,BEAM-T,3371,NaN,NaN,NaN,...,NaN,NaN,NaN,10x Datasets,https://www.10xgenomics.com/cn/datasets/10k-hu...,NaN,NaN,TCR+BCR,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HSS-180,HSSS_180,Synovial fluid,Synovial fluid,NaN,ICB Arthritis,Inflammation,3655,A*02:01:01,A*02:01:130,B*18:146,...,DQB1*05:01:01,DRB1*11:01:01,DRB1*01:01:01,Runci Wang et al.,DOI: 10.1126/sciimmunol.add1591,syn51602197,NaN,TCR,NaN,NaN
HSS-191,HSSS_191,Synovial fluid,Synovial fluid,NaN,ICB Arthritis,Inflammation,3370,A*01:01:38,A*01:319,B*51:165,...,DQB1*06:316,DRB1*13:313,DRB1*03:183,Runci Wang et al.,DOI: 10.1126/sciimmunol.add1591,syn51602197,NaN,TCR,NaN,NaN
HSS-219,HSSS_219,Synovial fluid,Synovial fluid,NaN,ICB Arthritis,Inflammation,2923,A*02:01:130,A*11:01:95,B*40:265N,...,DQB1*05:01:01,DRB1*13:275,DRB1*01:01:01,Runci Wang et al.,DOI: 10.1126/sciimmunol.add1591,syn51602197,NaN,TCR,NaN,NaN
RA-335L-CD8,RA-335,Synovial fluid,Synovial fluid,NaN,ICB Arthritis,Inflammation,459,A*11:69N,A*31:01:02,B*40:208,...,DQB1*06:02:01,DRB1*07:01:01,DRB1*15:01:01,Runci Wang et al.,DOI: 10.1126/sciimmunol.add1591,syn51602197,NaN,TCR,NaN,NaN
RA-335R-CD8,RA-335,Synovial fluid,Synovial fluid,NaN,ICB Arthritis,Inflammation,1541,A*11:01:95,A*31:01:02,B*40:01:02,...,DQB1*06:02:01,DRB1*07:100,DRB1*15:171:01,Runci Wang et al.,DOI: 10.1126/sciimmunol.add1591,syn51602197,NaN,TCR,NaN,NaN

In [4]:
#standard AIRR tsv fieds
col_names_airr = ['sequence_id', 'sequence', 'quality', 'sequence_aa', 'rev_comp', 'productive', 'vj_in_frame', 'stop_codon', 'complete_vdj', 'locus', 'v_call', 'd_call', 'd2_call', 'j_call', 'c_call', 'sequence_alignment', 'quality_alignment', 'sequence_alignment_aa', 'germline_alignment', 'germline_alignment_aa', 'junction', 'junction_aa', 'np1', 'np1_aa', 'np2', 'np2_aa', 'np3', 'np3_aa', 'cdr1', 'cdr1_aa', 'cdr2', 'cdr2_aa', 'cdr3', 'cdr3_aa', 'fwr1', 'fwr1_aa', 'fwr2', 'fwr2_aa', 'fwr3', 'fwr3_aa', 'fwr4', 'fwr4_aa', 'v_score', 'v_identity', 'v_support', 'v_cigar', 'd_score', 'd_identity', 'd_support', 'd_cigar', 'd2_score', 'd2_identity', 'd2_support', 'd2_cigar', 'j_score', 'j_identity', 'j_support', 'j_cigar', 'c_score', 'c_identity', 'c_support', 'c_cigar', 'v_sequence_start', 'v_sequence_end', 'v_germline_start', 'v_germline_end', 'v_alignment_start', 'v_alignment_end', 'd_sequence_start', 'd_sequence_end', 'd_germline_start', 'd_germline_end', 'd_alignment_start', 'd_alignment_end', 'd2_sequence_start', 'd2_sequence_end', 'd2_germline_start', 'd2_germline_end', 'd2_alignment_start', 'd2_alignment_end', 'j_sequence_start', 'j_sequence_end', 'j_germline_start', 'j_germline_end', 'j_alignment_start', 'j_alignment_end', 'c_sequence_start', 'c_sequence_end', 'c_germline_start', 'c_germline_end', 'c_alignment_start', 'c_alignment_end', 'cdr1_start', 'cdr1_end', 'cdr2_start', 'cdr2_end', 'cdr3_start', 'cdr3_end', 'fwr1_start', 'fwr1_end', 'fwr2_start', 'fwr2_end', 'fwr3_start', 'fwr3_end', 'fwr4_start', 'fwr4_end', 'v_sequence_alignment', 'v_sequence_alignment_aa', 'd_sequence_alignment', 'd_sequence_alignment_aa', 'd2_sequence_alignment', 'd2_sequence_alignment_aa', 'j_sequence_alignment', 'j_sequence_alignment_aa', 'c_sequence_alignment', 'c_sequence_alignment_aa', 'v_germline_alignment', 'v_germline_alignment_aa', 'd_germline_alignment', 'd_germline_alignment_aa', 'd2_germline_alignment', 'd2_germline_alignment_aa', 'j_germline_alignment', 'j_germline_alignment_aa', 'c_germline_alignment', 'c_germline_alignment_aa', 'junction_length', 'junction_aa_length', 'np1_length', 'np2_length', 'np3_length', 'n1_length', 'n2_length', 'n3_length', 'p3v_length', 'p5d_length', 'p3d_length', 'p5d2_length', 'p3d2_length', 'p5j_length', 'v_frameshift', 'j_frameshift', 'd_frame', 'd2_frame', 'consensus_count', 'duplicate_count', 'umi_count', 'cell_id', 'clone_id', 'repertoire_id', 'sample_processing_id', 'data_processing_id', 'rearrangement_id', 'rearrangement_set_id', 'germline_database']

#turn tcr adata obs df into df with AIRR tsv columns
clonotype_df = tcr_adat.obs
airr_df = clonotype_df.melt(
    id_vars=["individual", "number_of_cells", "tcr", "TRAV", "TRAJ", "TRBV", "TRBJ"],
    value_vars=["CDR3a", "CDR3b"],
    var_name="chain_tmp",
    value_name="cdr3_aa"
)

# Map chain_tmp to locus (one locus type per row)
airr_df["locus"] = airr_df["chain_tmp"].map({
    "CDR3a": "TRA",
    "CDR3b": "TRB"
})

# Assign V/J
airr_df["v_call"] = np.where(airr_df["locus"]=="TRA", airr_df["TRAV"], airr_df["TRBV"])
airr_df["j_call"] = np.where(airr_df["locus"]=="TRA", airr_df["TRAJ"], airr_df["TRBJ"])

# use tcr as sequence id adding locus type to end
airr_df["sequence_id"] = airr_df["tcr"] + "_" + airr_df["locus"]

airr_df.rename(columns={
    "number_of_cells": "duplicate_count",
    "individual": "repertoire_id"
}, inplace=True)

airr_df.drop(columns=["TRAV", "TRAJ", "TRBV", "TRBJ", "chain_tmp","tcr"], inplace=True)

# Add any missing columns in airr_df with NaN
airr_df = airr_df.reindex(columns=col_names_airr)
airr_df

,sequence_id,sequence,quality,sequence_aa,rev_comp,productive,vj_in_frame,stop_codon,complete_vdj,locus,...,duplicate_count,umi_count,cell_id,clone_id,repertoire_id,sample_processing_id,data_processing_id,rearrangement_id,rearrangement_set_id,germline_database
0,CAAAA=CASSYSTGEGKYF=TRAV13-1=TRAJ48=TRBV6-5=TR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRA,...,1,NaN,NaN,NaN,F021,NaN,NaN,NaN,NaN,NaN
1,CAAAAAAGNKLTF=CASSLSVDGYTF=TRAV23DV6=TRAJ17=TR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRA,...,1,NaN,NaN,NaN,PEM6,NaN,NaN,NaN,NaN,NaN
2,CAAAAAGGTSYGKLTF=CASSLPGREAFF=TRAV23DV6=TRAJ52...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRA,...,1,NaN,NaN,NaN,COV_010,NaN,NaN,NaN,NaN,NaN
3,CAAAAAGKSTF=CASSQGDSSYEQYF=TRAV12-2=TRAJ27=TRB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRA,...,1,NaN,NaN,NaN,IpiNivo_Resistant,NaN,NaN,NaN,NaN,NaN
4,CAAAAAGNKLTF=CASSGDPIVGEQFF=TRAV13-1=TRAJ17=TR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRA,...,1,NaN,NaN,NaN,PBMC_C_HD2,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795891,CYYDKVIF=CSARAIAGGPPETQYF=TRAV12-3=TRAJ50=TRBV...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRB,...,1,NaN,NaN,NaN,NPC_SC_1813,NaN,NaN,NaN,NaN,NaN
2795892,CYYGNNRLAF=CASSFRTAKNIQYF=TRAV8-3=TRAJ7=TRBV19...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRB,...,7,NaN,NaN,NaN,PT_1,NaN,NaN,NaN,NaN,NaN
2795893,CYYPYKLSF=CASSIGGTEAFF=TRAV12-1=TRAJ20=TRBV19=...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRB,...,1,NaN,NaN,NaN,IpiNivo_Resistant,NaN,NaN,NaN,NaN,NaN
2795894,CYYSATGNQFYF=CASSPGGLVNEQFF=TRAV24=TRAJ49=TRBV...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRB,...,1,NaN,NaN,NaN,UPN10,NaN,NaN,NaN,NaN,NaN
2795895,CYYSGGYQKVTF=CAISESKSGAEKLFF=TRAV25=TRAJ13=TRB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRB,...,1,NaN,NaN,NaN,su001,NaN,NaN,NaN,NaN,NaN

In [5]:
#turn df individual IDs into str to avoid issues
df["Individual ID"] = df["Individual ID"].astype(str)

#get the individuals (both healthy and unhealthy) from studies that study the given target disease
def get_disease_individuals(target_disease: str, meta: pd.DataFrame):
    mask = (
        df
        .groupby("Author")["Disease Metatype"]
        .transform(lambda x: x.eq(target_disease).any())
    )

    result = df[mask]
    individual_list = (result.groupby(["Author", "Disease Metatype"])["Individual ID"].unique())
    print(individual_list)

    return individual_list.to_dict()

In [6]:
#create AIRR tsv files per individual

def create_tsv_individual(disease_ind_dict, target_disease, airr_dataframe, meta_df, create_tsv=False, tsv_path=None):
    metadata_for_csv = pd.DataFrame(columns=["subject_id", "disease", "disease_metatype", "author", "disease_status","filename"])
   
    for (author, disease), individuals in disease_ind_dict.items():
        label = "positive" if disease == target_disease else "negative"
        
        for individual in individuals:
            individual = str(individual)

            #get the first list item because one individual may have several samples
            metadata_values = meta_df.loc[meta_df["Individual ID"]==individual, ["Individual ID", "Disease", "Disease Metatype", "Author"]].values.tolist()[0]
            
            #get the section relevant for the individual
            ind_df = airr_dataframe[airr_dataframe["repertoire_id"] == individual]
            file_name = f"{target_disease}_{label}_{individual}.tsv"

            #metadata for immuneml (this will be cocatenated with other disease metadata)
            metadata_values.extend([label,file_name])
            metadata_for_csv.loc[len(metadata_for_csv)] = metadata_values
            
            if create_tsv:
                ind_df.to_csv(tsv_path + file_name,sep="\t",index=False)

    return metadata_for_csv

In [7]:
covid19_dict = get_disease_individuals("COVID-19", df)

Author                         Disease Metatype
Anastasia A. Minervina et al.  COVID-19                    [2169460_SJTRC_InfVax_1, 2169461_SJTRC_InfVax_...
Chanchan Xiao et al.           COVID-19                                                  [E357, n_sp1, I757]
Florian Bieberich et al.       COVID-19                                         [B1, B2, B3, B4, B5, B6, B7]
In Su Cheon et al.             COVID-19                    [COVID_19_PBMC_BAL_donor_2, COVID_19_PBMC_BAL_...
Jolie M. Phan et al.           COVID-19                                                         [Seshadri02]
Joshua M. Francis et al.       COVID-19                    [201657852, 201657854, 201657856, RAGN898219, ...
                               Control (Francis et al.)    [2010113790, 2010113903, 108245, HHU20160714, ...
Mingfeng Liao et al.           COVID-19                    [C141, C142, C143, C144, C145, C146, C148, C14...
Petra Bacher et al.            COVID-19                    [J09835, J09836, J10535, J10624, J10625, J1088...
Samuele Notarbartolo  et al.   COVID-19                    [p1_mild, p2_mild, p3_mild, p4_severe, p5_seve...
                               Healthy                                                        [p7_HD, p8_HD]
Wen Wen, et al.                COVID-19                    [LRS5, LRS4, LRS3, LRS2, LRS1, ERS5, ERS4, ERS...
                               Healthy                                                            [HC2, HC1]
Weng Hua Khoo et al.           COVID-19                    [COV_001, COV_002, COV_007, COV_009, COV_010, ...
Xiaorui Wang et al.            COVID-19                    [C-21, C-22, C-19, C-20, C-23, C-24, C-25, C-2...
                               Healthy                     [H-1, H-2, H-3, H-4, H-5, H-6, H-7, H-8, H-9, ...
Name: Individual ID, dtype: object

In [ ]:
#use create_tsv=True once (create_tsv=False to just get the meta info)
covid19_meta = create_tsv_individual(
    disease_ind_dict=covid19_dict,
    target_disease="COVID-19",
    airr_dataframe=airr_df,
    meta_df=df,
    create_tsv=False,
    tsv_path="/vol/data/immuneML/tcr_atlas_data/covid19_leukemia/repertoires/")

covid19_meta

,subject_id,disease,disease_metatype,author,disease_status,filename
0,2169460_SJTRC_InfVax_1,COVID-19,COVID-19,Anastasia A. Minervina et al.,positive,COVID-19_positive_2169460_SJTRC_InfVax_1.tsv
1,2169461_SJTRC_InfVax_2,COVID-19,COVID-19,Anastasia A. Minervina et al.,positive,COVID-19_positive_2169461_SJTRC_InfVax_2.tsv
2,2169462_SJTRC_InfVax_3,COVID-19,COVID-19,Anastasia A. Minervina et al.,positive,COVID-19_positive_2169462_SJTRC_InfVax_3.tsv
3,2247114_JCC392_SJTRC_InfVaxBT_1_Rxn4,COVID-19,COVID-19,Anastasia A. Minervina et al.,positive,COVID-19_positive_2247114_JCC392_SJTRC_InfVaxB...
4,2247115_JCC392_SJTRC_InfVaxBT_2_Rxn5,COVID-19,COVID-19,Anastasia A. Minervina et al.,positive,COVID-19_positive_2247115_JCC392_SJTRC_InfVaxB...
...,...,...,...,...,...,...
166,H-7,"Control (Wang et al., 2022)",Healthy,Xiaorui Wang et al.,negative,COVID-19_negative_H-7.tsv
167,H-8,"Control (Wang et al., 2022)",Healthy,Xiaorui Wang et al.,negative,COVID-19_negative_H-8.tsv
168,H-9,"Control (Wang et al., 2022)",Healthy,Xiaorui Wang et al.,negative,COVID-19_negative_H-9.tsv
169,H-10,"Control (Wang et al., 2022)",Healthy,Xiaorui Wang et al.,negative,COVID-19_negative_H-10.tsv
170,H-11,"Control (Wang et al., 2022)",Healthy,Xiaorui Wang et al.,negative,COVID-19_negative_H-11.tsv

In [10]:
leukemia_dict = get_disease_individuals("Leukemia", df)

Author                Disease Metatype
Hussein Abbas et al.  Healthy                                                        [NL1, NL2]
                      Leukemia                         [PT1, PT2, PT3, PT4, PT5, PT6, PT7, PT8]
Shouguo Gao et al.    Control (Gao et al.)                                      [HD5, HD6, HD7]
                      Healthy                                              [HD1, HD2, HD3, HD4]
                      Leukemia                [UPN24, UPN10, UPN19, UPN18, UPN4, UPN17, UPN1...
Tobias Roider et al.  Leukemia                [18LN0078, 18LN0104, 18LN0110, 18LN0132, 19LN0...
Xiaofang Wang et al.  Leukemia                         [B_ALL_h2, B_ALL_p1, B_ALL_p2, B_ALL_p3]
Name: Individual ID, dtype: object

In [ ]:
leukemia_meta = create_tsv_individual(
    disease_ind_dict=leukemia_dict,
    target_disease="Leukemia",
    airr_dataframe=airr_df,
    meta_df=df,
    create_tsv=False,
    tsv_path="/vol/data/immuneML/tcr_atlas_data/covid19_leukemia/repertoires/")

leukemia_meta

,subject_id,disease,disease_metatype,author,disease_status,filename
0,NL1,Control (Abbas et al.),Healthy,Hussein Abbas et al.,negative,Leukemia_negative_NL1.tsv
1,NL2,Control (Abbas et al.),Healthy,Hussein Abbas et al.,negative,Leukemia_negative_NL2.tsv
2,PT1,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT1.tsv
3,PT2,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT2.tsv
4,PT3,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT3.tsv
5,PT4,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT4.tsv
6,PT5,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT5.tsv
7,PT6,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT6.tsv
8,PT7,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT7.tsv
9,PT8,AML,Leukemia,Hussein Abbas et al.,positive,Leukemia_positive_PT8.tsv
10,HD5,Control (Gao et al.),Control (Gao et al.),Shouguo Gao et al.,negative,Leukemia_negative_HD5.tsv
11,HD6,Control (Gao et al.),Control (Gao et al.),Shouguo Gao et al.,negative,Leukemia_negative_HD6.tsv
12,HD7,Control (Gao et al.),Control (Gao et al.),Shouguo Gao et al.,negative,Leukemia_negative_HD7.tsv
13,HD1,Control (Gao et al.),Healthy,Shouguo Gao et al.,negative,Leukemia_negative_HD1.tsv
14,HD2,Control (Gao et al.),Healthy,Shouguo Gao et al.,negative,Leukemia_negative_HD2.tsv
15,HD3,Control (Gao et al.),Healthy,Shouguo Gao et al.,negative,Leukemia_negative_HD3.tsv
16,HD4,Control (Gao et al.),Healthy,Shouguo Gao et al.,negative,Leukemia_negative_HD4.tsv
17,UPN24,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN24.tsv
18,UPN10,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN10.tsv
19,UPN19,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN19.tsv
20,UPN18,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN18.tsv
21,UPN4,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN4.tsv
22,UPN17,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN17.tsv
23,UPN1,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN1.tsv
24,UPN12,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN12.tsv
25,UPN8,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN8.tsv
26,UPN13,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN13.tsv
27,UPN14,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN14.tsv
28,UPN15,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN15.tsv
29,UPN6,Large granular lymphocyte leukemia,Leukemia,Shouguo Gao et al.,positive,Leukemia_positive_UPN6.tsv
30,18LN0078,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_18LN0078.tsv
31,18LN0104,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_18LN0104.tsv
32,18LN0110,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_18LN0110.tsv
33,18LN0132,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_18LN0132.tsv
34,19LN0144,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_19LN0144.tsv
35,19LN0178,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_19LN0178.tsv
36,19LN0193,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_19LN0193.tsv
37,19LN0198,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_19LN0198.tsv
38,20LN0217,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0217.tsv
39,20LN0243,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0243.tsv
40,20LN0249,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0249.tsv
41,20LN0259,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0259.tsv
42,20LN0264,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0264.tsv
43,20LN0278,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_20LN0278.tsv
44,21LN0302,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_21LN0302.tsv
45,21LN0343,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_21LN0343.tsv
46,22LN0417,Nodal B cell lymphoma,Leukemia,Tobias Roider et al.,positive,Leukemia_positive_22LN0417.tsv
47,B_ALL_h2,B-ALL,Leukemia,Xiaofang Wang et al.,positive,Leukemia_positive_B_ALL_h2.tsv
48,B_ALL_p1,B-ALL,Leukemia,Xiaofang Wang et al.,positive,Leukemia_positive_B_ALL_p1.tsv
49,B_ALL_p2,B-ALL,Leukemia,Xiaofang Wang et al.,positive,Leukemia_positive_B_ALL_p2.tsv
50,B_ALL_p3,B-ALL,Leukemia,Xiaofang Wang et al.,positive,Leukemia_positive_B_ALL_p3.tsv

In [ ]:
#save the seperate metadata files
#covid19_meta.to_csv("/vol/data/immuneML/tcr_atlas_data/metadata_per_disease/covid19_metadata.csv", index=False)
#leukemia_meta.to_csv("/vol/data/immuneML/tcr_atlas_data/metadata_per_disease/leukemia_metadata.csv", index=False)
#
#covid19_leukemia_meta = pd.concat([covid19_meta, leukemia_meta], axis=0)
#covid19_leukemia_meta.to_csv("/vol/data/immuneML/tcr_atlas_data/covid19_leukemia/covid19_leukemia_metadata.csv", index=False)